config/routes.rb
Rails.application.routes.draw do
  
  root 'products#index'
  
  resources :products
  
  get 'static_pages/test'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
    
  get 'static_pages/landing_page'
    
  resources :orders, only: [:index, :show, :create, :destroy]

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
    has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image_url, :colour)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def landing_page
      @products = Product.limit(3)
#     @featured_product = Product.first
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="font_lato">
<head>
  <title>Appforlab</title>
  <!-- Google Fonts -->  
  <link href="http://fonts.googleapis.com/css?family=Lato:300" rel="stylesheet" type="text/css" />
  <link href='https://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
  <!-- Bootstrap CSS--> 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- CSS --> 
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Javascript --> 
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>  
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target=".navbar">
<!-- Fixed Toolbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Logo -->
                <%=link_to "Distingoo", static_pages_index_path, class: "navbar-brand" %>
            </div> <!-- /.navbar-header -->
            
            <div class="collapse navbar-collapse pull-right" id="navbar">
                <ul class="nav navbar-nav">
                    <li><%=link_to "Shop", static_pages_index_path%></li>
                    <li class="divider-vertical"></li>
                    <li><%=link_to "About", static_pages_about_path%></li>
                    <li class="divider-vertical"></li>
                    <li><%=link_to "Contact", static_pages_contact_path%></li>
                </ul>
            </div> <!-- /.collapse -->   
        </div> <!-- /.container -->    
    </div> <!-- /.navbar --> 
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
    <div class="row">
        <div class="col-md-1"><%= product.name %></div>
        <div class="col-md-5"><%= product.description %></div>
        <div class="col-md-1"><%= product.price %></div>
        <div class="col-md-1"><%= product.image_url %></div>
        <div class="col-md-1"><%= product.colour %></div>
        <div class="col-md-1"><%= link_to 'Show', product %></div>
        <div class="col-md-1"><%= link_to 'Edit', edit_product_path(product) %></div>
        <div class="col-md-1"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>    </div>
   </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h3 class="text-uppercase">Listing Products</h3>

<div class="container-fluid"> 
    <div class="row">
        <div class="col-md-1">Name</div>
        <div class="col-md-5">Description</div>
        <div class="col-md-1">Price</div>
        <div class="col-md-1">Image url</div>
        <div class="col-md-1">Colour</div>
        <div class="col-md-3">Manage</div>
    </div>
    <% @products.each do |product| %>
        <%= render partial: "product", locals: {product: product} %>
   <% end %>
</div>

<br>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/about.html.erb
<p>My name is Nizar Triki, a network and security consultant currently based in Montreal, Canada. <br/>I'm taking this course to enhance my web development skills.<br/>I hope combining these new skills to my designer eyes to build nice staff.</p>        
 

app/views/static_pages/contact.html.erb
<html>
<head></head>
<body style="background-color:lightgrey">
    <div> 
        <p> Address</p> 
        <p>650 Jean D'Estrees street,</br> H3C0G3 Montreal, Canada</p>
        <p>5145760020</p>
        <p> Email</p>
        <p>triki.nizar@gmail.com</p>
    </div>
</body>
</html>

app/views/static_pages/index.html.erb
<section id="models">  
    <div class = "container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 jewelry-item">
                <a href="#" class="jewelry-link" data-toggle="modal" data-target="#modalWork">
                    <div class="jewelry-hover">
                        <div class="jewelry-hover-content">
                            <i class="fa fa-plus fa-3x"></i>
                        </div>
                    </div>
                    <%=image_tag "model1.jpg", :class => "image-box" %>
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 jewelry-item">
                <a href="#" class="jewelry-link" data-toggle="modal" data-target="#modalWork">
                    <div class="jewelry-hover">
                        <div class="jewelry-hover-content">
                            <i class="fa fa-plus fa-3x"></i>
                        </div>
                    </div>
                    <%=image_tag "model2.jpg", :class => "image-box" %>
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 jewelry-item">
                <a href="#" class="jewelry-link" data-toggle="modal" data-target="#modalWork">
                    <div class="jewelry-hover">
                        <div class="jewelry-hover-content">
                            <i class="fa fa-plus fa-3x"></i>
                        </div>
                    </div>
                    <%=image_tag "model3.jpg", :class => "image-box" %>
                </a>
            </div>
 
      </div>
    </section> 

app/views/static_pages/landing_page.html.erb
<div class="container">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <% @products.each do |product| %>
        <li data-target="#carousel-example-generic" data-slide-to="0" class="<%= "active" if product == @products.first %>"></li>
      <% end %>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <% @products.each do |product| %>
      <div class="item<%= " active" if product == @products.first %>">
        <%= image_tag(product.image_url) %>
          <div class="carousel-caption">
            <%= product.name %>
          </div>
      </div>
      <% end %>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/static_pages/test.html.erb
<h1>StaticPages#test</h1>
<p>Find me in app/views/static_pages/test.html.erb</p>